[[pages]]
path = "src/menus/home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "src/menus/tarjima.py"
name = "Brayl tarjimon"
icon = "â„ï¸"

[[pages]]
path = "src/menus/tekshirgich.py"
name = "Tekshirgich"
icon = "âœ…"

[[pages]]
path = "src/menus/generatsiya.py"
name = "Nutqqa generatsiya"
icon = "ğŸ“•"

[[pages]]
path = "src/menus/pydantic.py"
name = "Sozlamalar"
icon = "ğŸ”§"